# Site settings
title: Lucianux
email: lucian303@gmail.com
description: > Lucianux: Lucian++ Linux. Software Consulting.
baseurl: ""
url: "http://lucianux.com"
twitter_username: lucianux
github_username:  lucian303

# Build settings
markdown: kramdown
